package autojson.bind;

import autojson.stream.JsonGenerator;
import autojson.stream.JsonToken;

import javax.annotation.Nullable;
import java.io.IOException;

/**
 * Maps an object to JSON.
 *
 * @param <T> the object type can be written by this writer
 */
public interface ValueWriter<T> {

    /**
     * Writes the given value to the generator.
     * If value is null, {@link JsonToken#NULL} will be written.
     * JSON generated by this method will be valid standalone JSON.
     */
    void write(JsonGenerator generator, @Nullable T value) throws IOException;

}
